version: 2.1

executors:
  pw-jammy-development:
    docker:
      - image: mcr.microsoft.com/playwright:v1.38.0-jammy
    resource_class: medium

jobs:
  build:
    executor: pw-jammy-development
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm ci
      - run:
          name: Run Playwright Tests
          command: npm run e2e:run

workflows:
  version: 2
  build_and_test:
    jobs:
      - build